#!/usr/bin/env bash

# Simple Nagios plugin to test the local network address of a connected CCTV camera and ensure it is accessible

cameraIP=$(ifconfig wlan0 > /dev/null 2>&1 | grep "inet addr" | cut -d ':' -f2 | cut -d ' ' -f1 | cut -d '.' -f 1-3)

# All CCTV will be set to the *.*.*.123
netcat $cameraIP.123 88 > /dev/null 2>&1

if [ $? != 0 ]; then
    echo "WARNING - CCTV appears to be down"
    exit 1
else
    echo "OK - CCTV is accessible"
    exit 0
fi

