#!/usr/bin/env bash

# Simple Nagios plugin to check that new snapshots are coming into the CCTV folder

NUM_FILES_1=$(ls -1 /mnt/cctv/*/snap/* | wc -l)
sleep 2
NUM_FILES_2=$(ls -1 /mnt/cctv/*/snap/* | wc -l)

if [ "$NUM_FILES_1" == "$NUM_FILES_2" ]; then
	echo "CRITICAL - CCTV not uploading"
	exit 2
else
	echo "OK - CCTV running"
	exit 0
fi
